name: Publish Retype powered website to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish:
    name: Publish to retype branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - run: |
          dpkg-deb -b --root-owner-group bashrun
          mv bashrun.deb src/static/
      - uses: retypeapp/action-build@latest
        with:
          config_path: src/
      - run: |
          find /tmp/tmp.* -type f -name retype.css
          sed -i '/dark-850: #1e1e1e/dark-850: #000/' "$(find /tmp/tmp.* -type f -name retype.css)"
          sed -i 's/121212/000/' "$(find /tmp/tmp.* -type f -name retype.css)" # background
          sed -i 's/222/00210e/' "$(find /tmp/tmp.* -type f -name retype.css)" # code
      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
      - uses: otto-de/purge-deprecated-workflow-runs@v2
        with:
          remove-cancelled: true
          remove-failed: true
          remove-obsolete: true
          token: ${{ secrets.PAT }}
          remove-older-than: 1d