name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish to retype branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - run: |
          dpkg-deb -b --root-owner-group bashrun
          mv bashrun.deb src/static/
      - uses: retypeapp/action-build@latest
        with:
          config_path: src/
      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true